# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a34c097d93bb9adc7964a070b077e661b929b4e0a84918539496674e022eb45e3a6be47b3a41b2fc186520168a3e1a66072b75cfb51c69eaf382be9d174bf5

test:
  secret_key_base: 7da824c24fd2de429aa3ac6c382db27a583615dfd3a52480b24e3981e53a427ea7bd9257a30173b7f985fad4bad7a42767af903008164f97884f9154a5c9471f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
